title: Nikhil Nayak
email: nikhilnayak98@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Nikhil Nayak a computer science pursuing student, interested in Machine Learning, TensorFlow, Virtual Reality.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nikhilnayak98.github.io" # the base hostname & protocol for your site

# Social
githubUsername: nikhilnayak98
twitterUsername: nikhilnayak98
facebookUsername: nicks.nikhil98
googleUsername: nikhilnayak98

# Build settings
markdown: kramdown

themeColor: purple # green, blue, orange, purple, grey
fixedNav: 'true' # true or false

permalink: /:year/:month/:title
markdown: kramdown
include: [_pages]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed
